//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar1._0._1.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLS
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int TABLE_ID { get; set; }
        public int DISH_LIST_ID { get; set; }
        public Nullable<int> TOTAL_PRICE { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
