//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar1._0._1.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISHES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISHES()
        {
            this.DISH_LIST = new HashSet<DISH_LIST>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISH_LIST> DISH_LIST { get; set; }
    }
}
